### ISSUE TITLE
some mixin optimizations

### ISSUE THREAD

**Issue by nxtdaydelivery** [inglettronald/DulkirMod#16]
https://github.com/inglettronald/DulkirMod/blob/master/src/main/java/dulkirmod/mixins/MixinEntity.java
why does this exist?

---
https://github.com/inglettronald/DulkirMod/blob/master/src/main/java/dulkirmod/mixins/MixinEntityRenderer.java
https://github.com/inglettronald/DulkirMod/blob/master/src/main/java/dulkirmod/mixins/MixinGuiUtils.java

please don't overwrite these methods. they break other mods in many cases. the effect can be achieved with injects.

please contact me on discord if you are unaware of how optimize these so that your mod works with other mods better.

**Comment by inglettronald** [comment]
> https://github.com/inglettronald/DulkirMod/blob/master/src/main/java/dulkirmod/mixins/MixinEntity.java why does this exist?

This was one of the first things added to dulkirmod and is a part of the custom animations (a legit feature) made by a cheat developer and embedded in one of his mods. For some reason MixinEntityLivingBase is extending MixinEntityLivingBase - not sure if this is necessary for something as I didn't look much into it at the time. (my intentions were never initially on growing this mod much in scale/publicity).

> https://github.com/inglettronald/DulkirMod/blob/master/src/main/java/dulkirmod/mixins/MixinEntityRenderer.java https://github.com/inglettronald/DulkirMod/blob/master/src/main/java/dulkirmod/mixins/MixinGuiUtils.java
> 
> please don't overwrite these methods. they break other mods in many cases. the effect can be achieved with injects.
> 
> please contact me on discord if you are unaware of how optimize these so that your mod works with other mods better.

Noted, I'll likely do so. Thanks for your time in writing feedback, I enjoy the opportunity to take advice and learn about mod creation stuff :)
