### ISSUE TITLE
White backround.

### ISSUE THREAD

**Issue by RzvGry2** [inglettronald/DulkirMod#18]
the mod breakes after i close my game and when i open it in the backround instead of seing stuff its just a white backround
![image_2023-06-02_045425023](https://github.com/inglettronald/DulkirMod/assets/135291245/eb202c9a-f2ac-4dd2-a4d5-2ed6d3e3eb58)

**Comment by inglettronald** [comment]
Try turning off Fast Render (in optifine) or HUD caching (in patcher) and see if either of those affect the behavior if you can. This is some sort of Oneconfig issue.
