### ISSUE TITLE
You are sending commands too fast! Please slow down. (22)

### ISSUE THREAD

**Issue by UnLebendiger** [inglettronald/DulkirMod#21]
Hello I get since I have the mod Dulkir this message 
(You are sending commands too fast! Please slow down. (27))
always in chat and it only happens when I have the Dulkir mod when 
I remove it I no longer get the message I think so it comes from the mod
 can someone help me how to get rid of it

**Comment by B892** [comment]
same

**Comment by inglettronald** [comment]
This is a compatibility issue with Hytils. For now I'd suggest removing one of the mods from your folder, because I have not had the time to figure out what is causing this (and don't use hytils myself). Sorry for the inconvenience!

**Comment by UnLebendiger** [comment]
Ok Thanks for the help
